updated developer page
mildredfakoya/intern01-24 pull request #30
Opened 2024-02-11 19:10 UTC by adieddygit

updated commit

2024-02-11 23:12 UTC, mildredfakoya requested changes

2024-02-11 23:12 UTC, mildredfakoya commented on css/developer.css
> +	width: auto;
use max-width if you use auto as the value for responsiveness.

2024-02-12 05:38 UTC, adieddygit commented
an update to the developer.css file with max-width: auto; in the artribute .dev_sidenav

2024-02-12 20:42 UTC, mildredfakoya approved these changes

2024-02-12 20:42 UTC, merged